spring.application.name=cctrs-backend

# ===============================
# DATABASE (H2 ? in memory)
# ===============================
spring.datasource.url=jdbc:h2:mem:cctrsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false

# ===============================
# H2 CONSOLE
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.cctrs.backend=DEBUG
logging.level.org.springframework=INFO

# ===============================
# MAIL (READS FROM .env)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${SMTP_USERNAME}

# ===============================
# ERROR DETAILS (DEV)
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always
